### ISSUE TITLE
Migrating Content with File Fields

### ISSUE THREAD

**Issue by awasson** [heddn/d8_custom_migrate#4]
This really is more of a documentation issue I am sure. 

I have been able to successfully use d8_custom_migrate as a starting point for creating migrations of reasonably complex content types and migrate-import and migrate-rollback are working exactly as they should however with a specific content type that requires a file field I am having trouble.

I am receiving the following error when I try to pass a path to the file to the file field.

`SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '/sites/default/files/filename.pdf' for column 'field_attached_files_target_id' at row 1: INSERT INTO {node__field_attached_files} (entity_id, revision_id, bundle, delta, langcode, field_attached_files_target_id, field_attached_files_display, field_attached_files_description) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7); Array ( [:db_insert_placeholder_0] => 4885 [:db_insert_placeholder_1] => 4885 [:db_insert_placeholder_2] => circular [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => /sites/default/files/filename.pdf [:db_insert_placeholder_6] => [:db_insert_placeholder_7] => ) (/Users/awasson/Sites/devdesktop/drupal-8-clean/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:756)`

It's obviously looking for an integer which leads me to think I'll need some sort of preprocessing to occur. Is there any documentation I can follow.

Thanks,
Andrew

**Comment by awasson** [comment]
Just adding detail to this issue so to find a solution.

In order to shed light on the mapping I have done, I've made a gist of my config/install/migrate_plus.migration.migrate_csv.yml file, which can be found here: https://gist.github.com/awasson/9617629f5027fd4e163c30527b8bc856

**Comment by awasson** [comment]
I'll just be posting my ramblings as I progress through this...

I've modified my mapping for the file attachment to use the d6_cck_file plugin as follows:

  field_attached_files:
    plugin: d6_cck_file
    source: attached_files

This has resulted in the following warnings during the migration and still no files to be migrated.

`Illegal string offset 'data' CckFile.php:72                          [warning]`
`Illegal string offset 'fid' CckFile.php:80                            [warning]`

**Comment by heddn** [comment]
See https://www.mtech-llc.com/blog/ada-hernandez/how-migrate-images-drupal-8-using-csv-source for a complete run down of how to migrate files.
