### ISSUE TITLE
error while importing the csv

### ISSUE THREAD

**Issue by shreya9215** [heddn/d8_custom_migrate#5]
Migration failed with source plugin exception: fopen(): Filename cannot be empty

**Comment by sreher** [comment]
I use this path:  
  path: public://xyz/units.csv
in the yml file. 
You have to put the file into 
  .../sites/default/files/xyz/units.csv
Make sure, the webserver can access it.

**Comment by heddn** [comment]
Yup, that's the solution by @sreher.
